### ISSUE TITLE
The error handling is not working correctly in some cases: 

### ISSUE THREAD

**Issue by bavramor** [sonicnkt/wpkg-gp-client#11]
The error handling is not working correctly in some cases: 
If I click on “check for updates” (translated) I get a “no updates” (translated) reply within less than a second.
In fact there are updates but the client has a connection problem. 
wpkg-gp log shows:
2018-08-24 13:52:07,197 - WpkgService - ERROR - Error when processing Named Pipe Client:
Traceback (most recent call last):
  File "WpkgServer.pyc", line 214, in DoProcessClient
  File "WpkgExecuter.pyc", line 101, in Query
  File "WpkgNetworkHandler.pyc", line 88, in connect_to_network_share
error: (86, 'WNetAddConnection2', 'The specified network logon is wrong (translated) ')

wpkg-gp client should pass these errors to the user instead of showing “no updates available”.

**Comment by sonicnkt** [comment]
Hi, 
you are right this should be displayed. Im not sure why this is not catched but i will try to recreate it and fix it in the future. 
Thanks for reporting this issue!
