### ISSUE TITLE
Problem with windows 10

### ISSUE THREAD

**Issue by theLOICofFRANCE** [sonicnkt/wpkg-gp-client#14]
Hello,

First thank you for your work.

The client does not work at startup:
```
2018-11-27 11:50:38,848 - WpkgService - DEBUG - Testing connection: successful
2018-11-27 11:50:38,848 - WpkgService - DEBUG - Config: Reading ConnectionSleepBeforeRetry: '5' from ini file
2018-11-27 11:50:38,848 - WpkgService - DEBUG - Config: Reading ConnectionTries: '7' from ini file
2018-11-27 11:50:38,848 - WpkgService - DEBUG - Trying to connect to share. 1 of 7
2018-11-27 11:50:39,190 - WpkgService - ERROR - Error when processing Named Pipe Client:
Traceback (most recent call last):
  File "WpkgServer.pyc", line 195, in DoProcessClient
  File "WpkgExecuter.pyc", line 96, in Execute
  File "WpkgNetworkHandler.pyc", line 85, in connect_to_network_share
error: (58, 'WNetAddConnection2', 'Le serveur sp\xe9cifi\xe9 ne peut pas ex\xe9cuter l\x92op\xe9ration demand\xe9e.')
```

Manual launch does not work: 
```
C:\Program Files\Wpkg-GP>wpkgpipeclient.exe -d ExecuteNoReboot
Initializing Wpkg-GP software installation

C:\Program Files\Wpkg-GP>Wpkg-GP-Test.exe
2018-11-27 12:05:29 Starting OpenSCManager
2018-11-27 12:05:29 Started OpenSCManager
2018-11-27 12:05:29 Starting OpenService
2018-11-27 12:05:29 Started OpenService
2018-11-27 12:05:29 Starting QueryServiceStatusEx
2018-11-27 12:05:29 Finished QueryServiceStatusEx
2018-11-27 12:05:29 Checking the status of the service
2018-11-27 12:05:29 Trying to run CreateFile on named pipe
2018-11-27 12:05:29 The pipe handle was valid, continuing
2018-11-27 12:05:29 Executing SetNamedPipeHandleState
2018-11-27 12:05:29 Sending message to pipe server
2018-11-27 12:05:29 Waiting for reply from pipe server
2018-11-27 12:05:29 Executing ReadFile on pipe
2018-11-27 12:05:29 Successfully read from pipe, retrieved Status Code 100
2018-11-27 12:05:29 Converting string to wchar_t
2018-11-27 12:05:29 Calling UpdateStatus
2018-11-27 12:05:29 Running UpdateStatus with no error code
2018-11-27 12:05:29 Info (no event log): Initializing Wpkg-GP software installation
2018-11-27 12:05:29 Executing ReadFile on pipe
2018-11-27 12:05:29 Other end closed the pipe, continuing
```

The following change in the register did not work:
`REG ADD "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Power" /V HiberbootEnabled /T REG_dWORD /D 0 /F`

The same thing:
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon]
"GpNetworkStartTimeoutPolicyValue"=dword:00000060
[HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\LanManWorkstation\Parameters]
"DNSNameResolutionRequired"=dword:00000000
"DomainCompatibilityMode"=dword:00000001
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\NetworkProvider\HardenedPaths]
"\\\\*\\netlogon"="RequireMutualAuthentication=0,RequireIntegrity=0,RequirePrivacy=0"
```

On the other hand, this works well:
```
set SOFTWARE=\\192.168.182.1\wpkg\softwares
set WPKGROOT=\\192.168.182.1\wpkg\
cscript \\192.168.182.1\wpkg\wpkg.js /synchronize /nonotify /quiet
```

Do you have any idea how to fix this? In the worst case, I'll use the task scheduler...

**Comment by theLOICofFRANCE** [comment]
Duplicate: 
https://github.com/sonicnkt/wpkg-gp/issues/2

Sorry, I created in the wrong place.
